{
 "title": "V2Ray Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(count_over_time(v2ray_up[$__range]))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(count_over_time(v2ray_up{job=\"$job\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "V2Ray Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{job=~\"$job\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Real-Time Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "v2ray_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__range]))"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "V2Ray Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{job=~\"$job\",instance=~\"$instance\"}) - count(v2ray_up{job=~\"$job\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Real-Time User Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\", src!=\"all\"}[$__range])"
    }
   ]
  },
  {
   "title": "Real-Time Total Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\", src=\"all\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\", src=\"all\"}[$__range])"
    }
   ]
  },
  {
   "title": "Download Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src=\"all\"}[$__rate_interval])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users per Outbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src, target)",
     "legendFormat": "{{src}} <- {{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users per Outbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src,target)",
     "legendFormat": "{{src}} -> {{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Connect attempts of Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_connection_attempt_total{job=~\"$job\",instance=~\"$instance\",dimension=\"outbound\",src!=\"all\"}[$__rate_interval])) by (src,target)",
     "legendFormat": "{{src}} -> {{target}}"
    }
   ]
  }
 ]
}